import React, { createContext, useContext, useState } from 'react';

const translations = {
  ja: {
    tagline: '日本の心、一杯のお茶に',
    searchPlaceholder: 'お茶を検索...',
    login: 'ログイン',
    register: '新規登録',
    nav: ['ホーム', 'お茶コレクション', 'ギフト', '注文履歴', '私たちについて'],
    addToCart: 'カートに入れる',
    added: '追加しました！',
    footerTagline: '日本の心、一杯のお茶に',
    shop: 'ショップ',
    teaCollection: 'お茶コレクション',
    giftSets: 'ギフトセット',
    accessories: 'アクセサリー',
    newArrivals: '新商品',
    company: '会社情報',
    aboutUs: '私たちについて',
    ourStory: '私たちの物語',
    sustainability: 'サステナビリティ',
    careers: '採用情報',
    support: 'サポート',
    contactUs: 'お問い合わせ',
    faqs: 'よくある質問',
    shippingReturns: '配送・返品',
    privacyPolicy: 'プライバシーポリシー',
    copyright: 'Japanet Tea. 全著作権所有。',
    newsletterTitle: 'お茶の儀式に参加',
    newsletterDesc: '初回購入が10%オフ。',
    newsletterPlaceholder: 'メールアドレス',
    newsletterJoin: '登録',
    homeSubtitle: 'プレミアム日本茶',
    homeTitle: '日本茶の芸術',
    homeDesc: '日本各地の最高の茶園から厳選し、ご自宅に直接お届けします。',
    contactTitle: 'お問い合わせ',
    contactAddress: '長崎県、日本',
    contactEmail: 'support@japanettea.com',
    contactPhone: '+81 350 TEA 825',
    cartTitle: 'カート',
    cartEmpty: 'カートは空です',
    cartTotal: '合計',
    cartSubtotal: '小計',
    cartShipping: '送料',
    cartFree: '無料',
    cartBuy: '注文する',
    orderSummary: '注文内容',
    orderSuccess: 'ご注文ありがとうございます！',
    orderMsg: 'お茶をお届けいたします。ありがとうございました！',
    giftSet: 'ギフトセット',
    teaItem: 'お茶',
    ordersTitle: '注文履歴',
    ordersEmpty: 'まだ注文がありません',
    orderConfirmed: '確認済み',
    orderShipped: '発送済み',
    orderDelivered: '配達完了',
    viewOrders: '注文を見る',
    pleaseLogin: 'カートに追加するにはログインしてください',
    loginRequired: 'ログインが必要です',
    loginToCart: 'カートを見るにはログインしてください',
    loginToOrders: '注文を見るにはログインしてください',
    logoutBtn: 'ログアウト',
    products: [
      { name: 'ダージリン・ファーストフラッシュ' },
      { name: 'アールグレイ・クラシック' },
      { name: '宇治抹茶・極み' },
      { name: 'リラックス・カモミール' },
    ],
    loginEmail: 'メールアドレス',
    loginEmailPlaceholder: 'メールアドレスを入力',
    loginPassword: 'パスワード',
    loginPasswordPlaceholder: 'パスワードを入力',
    rememberMe: 'ログイン情報を保存',
    forgotPassword: 'パスワードをお忘れですか？',
    loginButton: 'ログイン',
    orContinue: 'または',
    noAccount: 'アカウントをお持ちでないですか？',
    signUp: '新規登録',
    backToStore: 'ストアに戻る',
    registerName: 'お名前',
    registerNamePlaceholder: 'お名前を入力',
    registerPasswordPlaceholder: 'パスワードを作成',
    registerConfirmPassword: 'パスワード確認',
    registerConfirmPlaceholder: 'パスワードを再入力',
    registerButton: 'アカウント作成',
    registerSubtitle: '新しいアカウントを作成',
    agreeTerms: '利用規約に同意します',
    haveAccount: 'すでにアカウントをお持ちですか？',
    giftSubtitle: '厳選されたお茶のギフトコレクション',
    giftTitle: '大切な人に、おいしい健康を贈りましょう',
    giftDesc: '一つ一つ丁寧に厳選されたセットが、喜び・温もり・健康をお届けします — 美しいパッケージで、そのままギフトに。',
    giftOff: '10% OFF',
    giftIncludes: '🍃 内容',
    giftPerfectFor: '🎁 おすすめシーン',
    giftCollections: [
      { name: '伝統の朝セット', consistsOf: 'ダージリン、クラシック緑茶、力強いアッサム、温かいマサラ。', occasion: '家族の朝食や、充実した一日のスタートに最適。' },
      { name: '禅と長寿ボックス', consistsOf: '抹茶、アンチエイジング白茶、スリミングウーロン、デトックスハーブ。', occasion: 'シニアや健康志向の方への最高の贈り物。' },
      { name: 'リラクゼーションスイート', consistsOf: '心安らぐカモミール、ストレス解消アールグレイ、癒しのハーブミックス、緑茶。', occasion: '夜のくつろぎや、気持ちを込めた贈り物にぴったり。' },
      { name: 'プレミアム・アールグレイコレクション', consistsOf: 'アールグレイ、爽やか緑茶、繊細な白茶、力強いアッサム。', occasion: 'お茶の愛好家やクラシックティー好きにぴったり。' },
      { name: 'ウェルネスウォリアーパック', consistsOf: '活力の抹茶、デトックスハーブ、代謝促進ウーロン、心安らぐカモミール。', occasion: '健康意識の高い友人やフィットネス愛好家への思いやりギフト。' },
      { name: 'エグゼクティブ午後の逃避行', consistsOf: 'プレミアムダージリン、しなやかウーロン、上品な白茶、香り豊かなマサラ。', occasion: '上質な午後の休息を求める忙しいプロフェッショナルに。' },
    ],
    teaTitle: '心も体もリラックス、健康をサポート 🍵',
    teaLoading: 'Atlasに接続中...',
    teaNames: {
      coll1: 'ダージリンティー',
      coll2: 'アールグレイ',
      coll3: 'アッサムティー',
      coll4: 'カモミール',
      coll5: '抹茶',
      coll6: 'ウーロン茶',
      coll7: '緑茶',
      coll8: '白茶',
      coll9: 'マサラティー',
      coll10: 'ハーブミックス',
    },
    teaBenefits: {
      coll1: '消化と免疫力を改善',
      coll2: 'ストレスを軽減し心臓の健康を促進',
      coll3: 'エネルギーを高め集中力を向上',
      coll4: 'リラックスと睡眠をサポート',
      coll5: '抗酸化物質が豊富',
      coll6: '体重管理をサポート',
      coll7: '代謝を改善',
      coll8: 'アンチエイジング効果',
      coll9: '免疫力を高め体を温める',
      coll10: 'デトックスとリラックス',
    },
  },
  en: {
    tagline: 'The heart of Japan, in a cup of tea',
    searchPlaceholder: 'Search our teas...',
    login: 'Log in',
    register: 'Register',
    nav: ['Home', 'Tea Collection', 'Gifts', 'Orders', 'About Us'],
    addToCart: 'Add to Cart',
    added: 'Added!',
    footerTagline: 'The heart of Japan, in a cup of tea',
    shop: 'Shop',
    teaCollection: 'Tea Collection',
    giftSets: 'Gift Sets',
    accessories: 'Accessories',
    newArrivals: 'New Arrivals',
    company: 'Company',
    aboutUs: 'About Us',
    ourStory: 'Our Story',
    sustainability: 'Sustainability',
    careers: 'Careers',
    support: 'Support',
    contactUs: 'Contact Us',
    faqs: 'FAQs',
    shippingReturns: 'Shipping & Returns',
    privacyPolicy: 'Privacy Policy',
    copyright: 'Japanet Tea. All rights reserved.',
    newsletterTitle: 'Join the Ceremony',
    newsletterDesc: 'Get 10% off your first harvest.',
    newsletterPlaceholder: 'Email Address',
    newsletterJoin: 'JOIN',
    homeSubtitle: 'PREMIUM JAPANESE TEA',
    homeTitle: 'The Art of Japanese Tea',
    homeDesc: 'Carefully sourced from the finest tea gardens across Japan, delivered directly to your door.',
    contactTitle: 'Contact',
    contactAddress: 'Nagasaki, Japan',
    contactEmail: 'support@japanettea.com',
    contactPhone: '+81 350 TEA 825',
    cartTitle: 'Your Cart',
    cartEmpty: 'Your cart is empty',
    cartTotal: 'Total',
    cartSubtotal: 'Subtotal',
    cartShipping: 'Shipping',
    cartFree: 'Free',
    cartBuy: 'Place Order',
    orderSummary: 'Order Summary',
    orderSuccess: 'Order Placed Successfully!',
    orderMsg: 'Thank you for your purchase. Your tea is on its way!',
    giftSet: 'Gift Set',
    teaItem: 'Tea',
    ordersTitle: 'Your Orders',
    ordersEmpty: 'No orders yet',
    orderConfirmed: 'Confirmed',
    orderShipped: 'Shipped',
    orderDelivered: 'Delivered',
    viewOrders: 'View Orders',
    pleaseLogin: 'Please log in to add items to cart',
    loginRequired: 'Login Required',
    loginToCart: 'Please log in to view your cart',
    loginToOrders: 'Please log in to view your orders',
    logoutBtn: 'Logout',
    products: [
      { name: 'Darjeeling First Flush' },
      { name: 'Earl Grey Classic' },
      { name: 'Uji Matcha Premium' },
      { name: 'Relax Chamomile' },
    ],
    loginEmail: 'Email Address',
    loginEmailPlaceholder: 'Enter your email',
    loginPassword: 'Password',
    loginPasswordPlaceholder: 'Enter your password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    loginButton: 'Log in',
    orContinue: 'or continue with',
    noAccount: "Don't have an account?",
    signUp: 'Sign up',
    backToStore: 'Back to store',
    registerName: 'Full Name',
    registerNamePlaceholder: 'Enter your name',
    registerPasswordPlaceholder: 'Create a password',
    registerConfirmPassword: 'Confirm Password',
    registerConfirmPlaceholder: 'Re-enter your password',
    registerButton: 'Create Account',
    registerSubtitle: 'Create your new account',
    agreeTerms: 'I agree to the Terms & Conditions',
    haveAccount: 'Already have an account?',
    giftSubtitle: 'Curated Tea Gift Collections',
    giftTitle: 'Gift your family and friends with delicious health',
    giftDesc: 'Each set is carefully curated to bring joy, warmth, and wellness — beautifully packaged and ready to gift.',
    giftOff: '10% OFF',
    giftIncludes: '🍃 Includes',
    giftPerfectFor: '🎁 Perfect for',
    giftCollections: [
      { name: 'The Traditional Morning Set', consistsOf: 'Darjeeling, Classic Green, Robust Assam, and Warming Masala.', occasion: 'Best for family breakfast gatherings or a productive start at the office.' },
      { name: 'Zen & Longevity Box', consistsOf: 'Ceremonial Matcha, Anti-aging White Tea, Slimming Oolong, and Detox Herbal.', occasion: 'A perfect health-focused gift for seniors or wellness enthusiasts.' },
      { name: 'The Relaxation Suite', consistsOf: 'Calming Chamomile, Stress-reducing Earl Grey, Soothing Herbal Mix, and Green Tea.', occasion: 'Ideal for evening winding down or a thoughtful \'Thinking of You\' gesture.' },
      { name: 'Premium Earl Lover\'s Collection', consistsOf: 'Earl Grey, Fresh Green Tea, Delicate White Tea, and Robust Assam.', occasion: 'Perfect for tea connoisseurs and classic tea lovers.' },
      { name: 'Wellness Warrior Pack', consistsOf: 'Energizing Matcha, Detox Herbal, Metabolism-boosting Oolong, and Calming Chamomile.', occasion: 'A thoughtful gift for health-conscious friends and fitness enthusiasts.' },
      { name: 'Executive\'s Afternoon Escape', consistsOf: 'Premium Darjeeling, Silky Oolong, Elegant White Tea, and Aromatic Masala.', occasion: 'Designed for busy professionals who deserve a quality afternoon break.' },
    ],
    teaTitle: 'Make yourself comfortable and improve your health 🍵',
    teaLoading: 'Connecting to Atlas...',
    teaNames: {
      coll1: 'Darjeeling Tea',
      coll2: 'Earl Grey',
      coll3: 'Assam Tea',
      coll4: 'Chamomile',
      coll5: 'Matcha',
      coll6: 'Oolong Tea',
      coll7: 'Green Tea',
      coll8: 'White Tea',
      coll9: 'Masala Tea',
      coll10: 'Herbal Mix',
    },
    teaBenefits: {},
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('ja');
  const t = translations[lang];
  const toggleLang = () => setLang((prev) => (prev === 'ja' ? 'en' : 'ja'));

  return (
    <LanguageContext.Provider value={{ lang, t, toggleLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
